src/Web/ViewModels/CertificateViewModel.cs
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels;

public class CertificateViewModel
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Required")]
    [Display(Name = "AwardTitle")]
    [MaxLength(100)]
    [RegularExpression(@"[^&<>\/]*$", ErrorMessage = "RegularExpression")]
    public string Title { get; set; } = string.Empty;

    [Required(ErrorMessage = "Required")]
    [Display(Name = "AwardDescription")]
    [MaxLength(200)]
    [RegularExpression(@"[^&<>\/]*$", ErrorMessage = "RegularExpression")]
    public string Description { get; set; } = string.Empty;

    [Display(Name = "Date")]
    [DataType(DataType.Date)]
    public DateTime Date { get; set; }

    public List<Link>? Links { get; set; }

    [Display(Name = "File")]
    [DataType(DataType.Upload)]
    public IFormFile? File { get; set; }

    public string Path { get; set; } = string.Empty;

    public string UniqueUrl { get; set; } = string.Empty;

    public string UserId { get; set; } = string.Empty;

    [Display(Name = "Stage")]
    public Stage Stage { get; set; }

    public int Page { get; set; }
}

src/Web/Controllers/Api/DownloadController.cs
using ApplicationCore.Entities.Identity;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using OfficeOpenXml;
using System.IO;
using System.IO.Compression;
using System.Net.Mime;
using System.Threading.Tasks;
using Web.Interfaces;


namespace Web.Controllers;

[Authorize]
[ApiController]
[Route("[controller]/[action]")]
public class DownloadController : ControllerBase
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly ICertificateRepository _repository;
    private readonly IStringLocalizer<SharedResource> _localizer;
    private readonly IStageService _stage;
    private readonly IWebHostEnvironment _appEnvironment;


    public DownloadController(UserManager<ApplicationUser> userManager,
                              ICertificateRepository repository,
                              IStringLocalizer<SharedResource> localizer,
                              IStageService stage,
                              IWebHostEnvironment appEnvironment)
    {
        _userManager = userManager;
        _repository = repository;
        _localizer = localizer;
        _stage = stage;
        _appEnvironment = appEnvironment;
    }


    [HttpGet("{id}")]
    public async Task<FileResult?> Jpg(int id)
    {
        var _user = await _userManager.GetUserAsync(User);

        var certificate = await _repository.GetByUserIdAsync(id, _user.Id);

        if (certificate is null)
        {
            return default;
        }

        return File(certificate.Path, MediaTypeNames.Image.Jpeg, certificate.Title + ".jpg");
    }


    [HttpGet]
    public async Task<FileResult?> Zip()
    {
        var _user = await _userManager.GetUserAsync(User);

        var list = _repository.ListByUserId(_user.Id);

        if (list is null)
        {
            return default;
        }

        // Creating an archive. 
        var compressedFileStream = new MemoryStream();
        (int count, string lastName) itemInfo = (0, string.Empty);

        using (var zipArchive = new ZipArchive(compressedFileStream, ZipArchiveMode.Create, false))
        {
            foreach (var item in list)
            {
                string fileName = string.Empty;

                if (itemInfo.count == 0)
                {
                    // For the first time, we simply name the itemInfo.lastName.
                    itemInfo.lastName = item.Title;
                    fileName = itemInfo.lastName;
                }
                else
                {
                    // If identical names are found, then add a serial number.
                    fileName = itemInfo.lastName == item.Title ? item.Title + "_" + itemInfo.count : item.Title;
                }

                itemInfo.count++;

                var zipEntry = zipArchive.CreateEntry(fileName + ".jpg");

                using var originalFileStream = new MemoryStream(
                    System.IO.File.ReadAllBytes(_appEnvironment.WebRootPath + item.Path));

                using var zipEntryStream = zipEntry.Open();
                originalFileStream.CopyTo(zipEntryStream);
            }
        }

        return File(compressedFileStream.ToArray(),
                    MediaTypeNames.Application.Zip,
                    _localizer["Achievements"] + ".zip");
    }


    [HttpGet]
    public async Task<FileResult?> Excel()
    {
        var _user = await _userManager.GetUserAsync(User);
        var certificates = _repository.ListByUserId(_user.Id);
        byte[]? data = default;
        int column = 2;
        int count = 1;

        // https://epplussoftware.com/developers/licenseexception
        ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

        using (var package = new ExcelPackage())
        {
            var worksheet = package.Workbook.Worksheets.Add("Sheet1");

            // Insert column names.
            worksheet.Cells[1, 1].Value = "№";
            worksheet.Cells[1, 2].Value = _localizer["AwardTitle"];
            worksheet.Cells[1, 3].Value = _localizer["Description"];
            worksheet.Cells[1, 4].Value = _localizer["Stage"];
            worksheet.Cells[1, 5].Value = _localizer["Date"];

            foreach (var c in certificates)
            {
                // Insert data.
                worksheet.Cells[column, 1].Value = count.ToString();
                worksheet.Cells[column, 2].Value = c.Title;
                worksheet.Cells[column, 3].Value = c.Description;
                worksheet.Cells[column, 4].Value = _stage.GetNameOfStage(c.Stage);
                worksheet.Cells[column, 5].Value = c.Date.ToShortDateString();

                column++;
                count++;
            }

            data = package.GetAsByteArray();
        }

        if (data is null || data.Length == 0)
        {
            return default;
        }

        return File(data,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    _localizer["Achievements"] + ".xlsx");
    }
}

src/Web/Controllers/CertificateController.cs
using ApplicationCore.Constants;
using ApplicationCore.Entities;
using ApplicationCore.Entities.Identity;
using ApplicationCore.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Web.Extensions;
using Web.Interfaces;
using Web.Models;
using Web.ViewModels;

namespace Web.Controllers;

[Authorize]
public class CertificateController : Controller
{
    private readonly ICertificateViewModelService _certificateService;
    private readonly ILogger<CertificateController> _logger;
    private readonly IStringLocalizer<SharedResource> _localizer;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly FileSettings _fileSettings;
    private readonly IWebHostEnvironment _appEnvironment;

    public CertificateController(ICertificateViewModelService certificateService,
                                 UserManager<ApplicationUser> userManager,
                                 IStringLocalizer<SharedResource> localizer,
                                 ILogger<CertificateController> logger,
                                 IOptions<FileSettings> options,
                                 IWebHostEnvironment appEnvironment)
    {
        _certificateService = certificateService;
        _userManager = userManager;
        _localizer = localizer;
        _logger = logger;
        _fileSettings = options.Value;
        _appEnvironment = appEnvironment;
    }


    public async Task<IActionResult> Index(int page = 1,
                                           string? year = null,
                                           string? find = null,
                                           Stage? stage = null)
    {
        var _user = await _userManager.GetUserAsync(User);

        return View(_certificateService.GetIndexViewModel(page, _user.Id, year, find, stage));
    }


    public async Task<IActionResult> Details(int id, CancellationToken cancellationToken, int page = 0)
    {
        page = GetCurrentPage(page);

        var _user = await _userManager.GetUserAsync(User);

        var certificate = await _certificateService.GetCertificateByIdIncludeLinksAsync(page,
                                                                                        id,
                                                                                        _user.Id,
                                                                                        cancellationToken);

        if (certificate is null)
        {
            return NotFound();
        }

        return View(certificate);
    }


    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CertificateViewModel cvm, CancellationToken cancellationToken)
    {
        var _user = await _userManager.GetUserAsync(User);

        if (cvm.File is null)
        {
            ModelState.AddModelError("File", _localizer["Required"]);
        }

        if (ModelState.IsValid)
        {
            ArgumentNullException.ThrowIfNull(cvm.File);

            if (cvm.File.CheckFileExtension(_fileSettings.Expansion))
            {
                ModelState.AddModelError("File", _localizer["FileExtensionError"]);
                return View();
            }

            using (var binaryReader = new BinaryReader(cvm.File.OpenReadStream()))
            {
                if (cvm.File.CheckFileSize(_fileSettings.MinSize, _fileSettings.SizeLimit))
                {
                    ModelState.AddModelError("File", _localizer["FileSizeError"]);
                    return View();
                }

                var path = $"/private/{Sha512Helper.GetRandomValue()}.jpg";

                using (var stream = System.IO.File.Create(_appEnvironment.WebRootPath + path))
                {
                    await cvm.File.CopyToAsync(stream, cancellationToken);
                }

                cvm.Path = path;
            }

            await _certificateService.CreateCertificateAsync(cvm, _user.Id, cancellationToken);

            _logger.LogInformation($"New certificate created by User {_user.Id}");

            return RedirectToAction(nameof(Index));
        }

        return View();
    }


    public async Task<IActionResult> Edit(int id, CancellationToken cancellationToken)
    {
        var _user = await _userManager.GetUserAsync(User);

        var certificate = await _certificateService.GetCertificateByIdAsync(id, _user.Id, cancellationToken);

        if (certificate is null)
        {
            return NotFound();
        }

        return View(certificate);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(CertificateViewModel cvm, CancellationToken cancellationToken)
    {
        var _user = await _userManager.GetUserAsync(User);

        if (ModelState.IsValid)
        {
            if (cvm.File != null)
            {
                if (cvm.File.CheckFileExtension(_fileSettings.Expansion))
                {
                    ModelState.AddModelError("File", _localizer["FileExtensionError"]);
                    return View(cvm);
                }

                using (var binaryReader = new BinaryReader(cvm.File.OpenReadStream()))
                {
                    if (cvm.File.CheckFileSize(_fileSettings.MinSize, _fileSettings.SizeLimit))
                    {
                        ModelState.AddModelError("File", _localizer["FileSizeError"]);
                        return View(cvm);
                    }

                    var path = $"/private/{Sha512Helper.GetRandomValue()}.jpg";

                    using (var stream = System.IO.File.Create(_appEnvironment.WebRootPath + path))
                    {
                        await cvm.File.CopyToAsync(stream, cancellationToken);
                    }

                    cvm.Path = path;
                }
            }

            try
            {
                await _certificateService.UpdateCertificateAsync(cvm, _user.Id, cancellationToken);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                _logger.LogError("An error occurred while updating the certificate: " + ex.Message);

                return RedirectToAction(nameof(Index));
            }

            _logger.LogInformation($"Certificate {cvm.Id} changed by User {_user.Id}");

            return RedirectToAction(nameof(Details), new { id = cvm.Id });
        }

        return View(cvm);
    }


    public IActionResult Delete()
    {
        return PartialView(nameof(Delete));
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id, CancellationToken cancellationToken)
    {
        int currentPage = GetCurrentPage();

        var _user = await _userManager.GetUserAsync(User);

        await _certificateService.DeleteCertificateAsync(id, _user.Id, cancellationToken);

        _logger.LogInformation($"Certificate {id} deleted by User {_user.Id}");

        return RedirectToAction(nameof(Index), new { page = currentPage });
    }


    public async Task<IActionResult> Share()
    {
        var _user = await _userManager.GetUserAsync(User);

        var callbackUrl = Url.Action("Index",
                                     "Public",
                                     new { uniqueUrl = _user.UniqueUrl },
                                     protocol: Request.Scheme);

        return Json(callbackUrl);
    }


    private int GetCurrentPage(int page = 0)
    {
        if (page == 0)
        {
            // Try get page from cookies.
            page = int.TryParse(HttpContext.Request.Cookies[CookieNamesConstants.Page],
                                out int result) ? result : 1;
        }
        else
        {
            HttpContext.Response.Cookies.Append(CookieNamesConstants.Page, 
                                                page.ToString(),
                                                new() { SameSite = SameSiteMode.Lax });
        }

        return page;
    }
}

src/Web/Controllers/LinkController.cs
using ApplicationCore.Entities.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.ViewModels;

namespace Web.Controllers;

[Authorize]
public class LinkController : Controller
{
    private readonly ILinkViewModelService _linkService;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly ILogger<LinkController> _logger;

    public LinkController(ILinkViewModelService linkService,
                          UserManager<ApplicationUser> userManager,
                          ILogger<LinkController> logger)
    {
        _linkService = linkService;
        _userManager = userManager;
        _logger = logger;
    }


    public async Task<IActionResult> Index(string id, CancellationToken cancellationToken)
    {
        var _user = await _userManager.GetUserAsync(User);

        var result = await _linkService.GetLinkListViewModelAsync(id, _user.Id, cancellationToken);

        if (result is null)
        {
            return NotFound();
        }

        return View(result);
    }


    public IActionResult Create(string id)
    {
        return View(new LinkViewModel { CertificateId = id });
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(LinkViewModel lvm, CancellationToken cancellationToken)
    {
        var _user = await _userManager.GetUserAsync(User);

        if (ModelState.IsValid)
        {
            var success = await _linkService.CreateLinkAsync(lvm, _user.Id, cancellationToken);

            if (!success)
            {
                return BadRequest();
            }

            _logger.LogInformation($"Link for the certificate {lvm.CertificateId} is created by User {_user.Id}");
        }

        return RedirectToAction(nameof(Index), new { id = lvm.CertificateId });
    }


    public IActionResult Delete()
    {
        return PartialView(nameof(Delete));
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(string id, string certificateId, CancellationToken cancellationToken)
    {
        var _user = await _userManager.GetUserAsync(User);

        var success = await _linkService.DeleteLinkAsync(id, certificateId, _user.Id, cancellationToken);

        if (!success)
        {
            return NotFound();
        }

        _logger.LogInformation($"Link for the certificate {certificateId} is deleted by User {_user.Id}");

        return RedirectToAction(nameof(Index), new { id = certificateId });
    }
}

src/Web/Views/Certificate/Create.cshtml
@model CertificateViewModel
@inject IStageService Service
@{
    ViewData["Title"] = Localizer["Title"];
}

<h1 class="caption">@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-7">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" accept="image/jpeg" />
                <label id="text" for="File" asp-for="File"></label>
                <p class="text-muted text-note float-right">@Localizer["Note"]</p>
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stage" class="control-label"></label>
                @Html.DropDownListFor(model => model.Stage, new SelectList(Service.GetStages(), "EnumName", "Name"), new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
            </div>
            <div class="form-group mt-1">
                <div class="btn-group" role="group">
                    <a class="btn btn-primary" asp-controller="Certificate" asp-action="Index">@Localizer["Back"]</a>
                    <input type="submit" value="@Localizer["Create"]" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script type="text/javascript" src="~/js/inputFile.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/js/autocomplete.js" asp-append-version="true"></script>
}

src/Web/Views/Certificate/Delete.cshtml
<form method="post" asp-controller="Certificate" asp-action="Delete">
    <div id="myModalBox" class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">@Localizer["Info"]</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            @Localizer["Message"]
        </div>
        <div class="modal-footer">
            <input type="submit" value="@Localizer["Yes"]" style="width:100px" class="btn btn-danger" />
            <button data-dismiss="modal" style="width:100px" class="btn btn-primary">@Localizer["Cancel"]</button>
        </div>
    </div>
</form>

src/Web/Views/Certificate/Details.cshtml
@model CertificateViewModel
@inject IStageService Service 
@{
    ViewData["Title"] = Localizer["Title"];
}

<partial name="MainPages/_DeleteModalPartial" />

<h1 class="caption">@Localizer["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-6 break-word">
        
        <partial name="MainPages/_CertificateDetailsPartial" model="@Model"/>

        <p>
            <a class="btn btn-info btn-sm mt-2 mb-3" 
               asp-controller="Link" 
               asp-action="Index" 
               asp-route-id="@Model.Id">@Localizer["Manage"]
            </a>
        </p>
        <div class="btn-group buttons-padding mb-3" role="group">
            <a asp-controller="Certificate" asp-action="Index" asp-route-page="@Model.Page" class="btn btn-primary">@Localizer["Back"]</a>
            <a asp-controller="Download" asp-action="Jpg" asp-route-id="@Model.Id" class="btn btn-primary">@Localizer["Download"]</a>
            <a asp-controller="Certificate" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">@Localizer["Change"]</a>
            <a asp-controller="Certificate" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger delete">@Localizer["Delete"]</a>
        </div>
    </div>
    <div class="col-md-6">
        <a href="@Url.Content(Model.Path)" data-lightbox="image-@Model.Id" data-title="@Model.Title">
            <img src="@Url.Content(Model.Path)" class="img-fluid img-thumbnail ms-image-details" />
        </a>
    </div>
</div>

@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.js" 
            integrity="sha512-UHlZzRsMRK/ENyZqAJSmp/EwG8K/1X/SzErVgPc0c9pFyhUwUQmoKeEvv9X0uNw8x46FxgIJqlD2opSoH5fjug==" 
            crossorigin="anonymous"
            referrerpolicy="no-referrer">
    </script>
    <script type="text/javascript" src="~/js/modalWindow.js" asp-append-version="true"></script>
}

src/Web/Views/Certificate/Edit.cshtml
@model CertificateViewModel
@inject IStageService Service
@{
    ViewData["Title"] = Localizer["Title"];
}

<h1 class="caption">@Localizer["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-7">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" />
            <input asp-for="Path" type="hidden" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" accept="image/jpeg" />
                <label id="text" for="File" asp-for="File"></label>
                <p class="text-muted text-note float-right">@Localizer["Note"]</p>
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stage" class="control-label"></label>
                @Html.DropDownListFor(model => model.Stage, new SelectList(Service.GetStages(), "EnumName", "Name"), new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
            </div>
            <div class="form-group mt-1">
                <div class="btn-group" role="group">
                    <a class="btn btn-primary" asp-controller="Certificate" asp-action="Details" asp-route-id="@Model.Id">@Localizer["Back"]</a>
                    <input type="submit" value="@Localizer["Change"]" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script type="text/javascript" src="~/js/inputFile.js" asp-append-version="true"></script>
    <script type="text/javascript" src="~/js/autocomplete.js" asp-append-version="true"></script>
}

src/Web/Views/Certificate/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = Localizer["Title"];
}

<h1 class="caption">@Localizer["Title"]</h1>

<div class="card mb-3">
    <div class="card-body">
        <div class="d-flex justify-content-between">
            <a class="btn btn-success width-12 bd-highlight" asp-controller="Certificate" asp-action="Create">
                @Localizer["Create"]
            </a>
            <a class="btn btn-light width-12 bd-highlight" style="cursor:pointer;" onclick="copy()">
                @Localizer["Copy"]
            </a>
        </div>
    </div>
</div>

<partial name="MainPages/_SearchPartial" model="@Model" />

@if (Model.Certificates.Any())
{
    <div class="row index">
        @foreach (var item in Model.Certificates)
        {
            <div class="col-sm-6">
                <div class="card mb-3 anim" onclick="start('@item.Id', @Model.PageViewModel.PageNumber)">
                    <partial name="MainPages/_CertificateCardPartial" model="item" />
                </div>
            </div>
        }
    </div>

    <page-link page-model="Model.PageViewModel" page-controller="Certificate" page-action="Index"></page-link>
}
else
{
    <partial name="MainPages/_EmptyListPartial" />
}

@section Scripts
{
    <script type="text/javascript" src="~/js/certificate.js" asp-append-version="true"></script>
}